/* eslint-disable @next/next/no-img-element */
"use client";
import {useEffect,useMemo,useState} from "react";
import {AnimatePresence,motion} from "framer-motion";
import {useSearchParams} from "next/navigation";
import Reveal from "@/components/Reveal";
import {useInvitation} from "@/components/InvitationProvider";
import {useMusicPlayer} from "@/hooks/useMusicPlayer";
import {useRsvpWishes,type Attendance} from "@/hooks/useRsvpWishes";
import type {GiftAccount,InvitationData} from "@/types/invitation";
import {Clapperboard,FilmReel,MarqueeStars} from "./PrismaticAccents";
import styles from "./style.module.css";

function Heading({over,title,dark=false}:{over:string;title:string;dark?:boolean}){return <Reveal><header className={`${styles.heading} ${dark?styles.headingDark:""}`}><span>{over}</span><h2>{title}</h2><div><i/>★<i/></div></header></Reveal>}
function Loading(){return <motion.div className={styles.loading} exit={{opacity:0}}><div className={styles.countLeader}><span>◇</span><i/><b>REFRACTING YOUR LOVE STORY</b></div></motion.div>}

function Cover({invitation}:{invitation:InvitationData}){const{setOpened}=useInvitation();const guest=useSearchParams().get("to")||"Bapak/Ibu/Saudara/i";return <motion.section className={styles.cover} initial={{opacity:0}} animate={{opacity:1}}>
 {invitation.coverImage&&<motion.img className={styles.coverImage} src={invitation.coverImage} alt={`Foto ${(invitation.groom.nickname || invitation.groom.name)} dan ${(invitation.bride.nickname || invitation.bride.name)}`} initial={{scale:1.1}} animate={{scale:1}} transition={{duration:2.5}}/>}<div className={styles.coverShade}/><div className={`${styles.curtain} ${styles.curtainLeft}`}/><div className={`${styles.curtain} ${styles.curtainRight}`}/><div className={styles.spotlight}/>
 <div className={styles.coverTop}><span>VISTIQ ATELIER</span><i>PRISMATIC EDITION</i></div>
 <motion.div className={styles.marquee} initial={{y:-25,opacity:0}} animate={{y:0,opacity:1}} transition={{delay:.25}}><MarqueeStars className={styles.marqueeLights}/><p>LOVE IN EVERY LIGHT</p><h1>{(invitation.groom.nickname || invitation.groom.name)}<span>&amp;</span>{(invitation.bride.nickname || invitation.bride.name)}</h1><b>{invitation.events[0]?.date}</b></motion.div>
 <motion.div className={styles.ticket} initial={{y:30,opacity:0}} animate={{y:0,opacity:1}} transition={{delay:.45}}><div className={styles.ticketMain}><small>EXCLUSIVELY FOR</small><strong>{guest}</strong><button onClick={()=>setOpened(true)}>OPEN THE PRISM <span>▶</span></button></div><div className={styles.ticketStub}><span>COLOR</span><b>AURA</b><i>2026</i></div></motion.div>
 </motion.section>}

function Opening({invitation}:{invitation:InvitationData}){return <div className={`${styles.section} ${styles.opening}`}><Clapperboard className={styles.openingClap}/><Heading over="First Light" title="Love, Refracted"/><div className={styles.synopsis}><Reveal><div className={styles.poster}>{invitation.coverImage&&<img src={invitation.coverImage} alt=""/>}<span>TWO HEARTS · INFINITE COLORS</span></div></Reveal><Reveal delay={.12}><article><small>OUR SPECTRUM</small><h3>One light.<br/>Two souls.<br/>Infinite love.</h3><p>Dengan memohon rahmat dan ridho Allah SWT, kami bermaksud menyelenggarakan pernikahan putra-putri kami, <b>{(invitation.groom.nickname || invitation.groom.name)}</b> dan <b>{(invitation.bride.nickname || invitation.bride.name)}</b>.</p><blockquote>“Dan di antara tanda-tanda kekuasaan-Nya ialah Dia menciptakan untukmu pasangan hidup supaya kamu mendapat ketenangan hati padanya.”<cite>QS. Ar-Rum : 21</cite></blockquote></article></Reveal></div></div>}

function StarCard({p,role}:{p:InvitationData["groom"]|InvitationData["bride"];role:string}){return <article className={styles.starCard}><div>{p.photo&&<img src={p.photo} alt={p.name}/>}<span>{role}</span></div><small>BELOVED</small><h3>{p.name}</h3>{p.parents&&<p>{role==="THE BRIDE"?"Putri":"Putra"} dari<br/>{p.parents}</p>}{p.instagram&&<a href={`https://instagram.com/${p.instagram.replace("@","")}`} target="_blank" rel="noreferrer">@{p.instagram.replace("@","")}</a>}</article>}
function Couple({invitation}:{invitation:InvitationData}){return <div className={styles.castBand}><div className={styles.section}><Heading over="Portraits In Light" title="Two Halves Of The Spectrum" dark/><Reveal><div className={styles.cast}><StarCard p={invitation.bride} role="THE BRIDE"/><span className={styles.castAnd}>&amp;</span><StarCard p={invitation.groom} role="THE GROOM"/></div></Reveal></div></div>}

function Story({invitation}:{invitation:InvitationData}){return <div className={styles.section}><Heading over="Chromatic Memories" title="Our Love In Chapters"/><div className={styles.scenes}>{invitation.story.map((s,i)=><Reveal key={`${s.year}-${s.title}`} delay={i*.08}><article><div className={styles.sceneHead}><b>CHAPTER {String(i+1).padStart(2,"0")}</b><span>GLOW {s.year}</span></div><h3>{s.title}</h3><p>{s.description}</p><small>FOREVER IN FOCUS</small></article></Reveal>)}</div></div>}

function Countdown({date}:{date:string}){const target=useMemo(()=>new Date(date).getTime(),[date]);const[now,setNow]=useState(()=>Date.now());useEffect(()=>{const id=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(id)},[]);const d=Math.max(0,target-now);const xs=[[Math.floor(d/864e5),"DAYS"],[Math.floor(d/36e5)%24,"HOURS"],[Math.floor(d/6e4)%60,"MINUTES"],[Math.floor(d/1e3)%60,"SECONDS"]];return <div className={styles.countdown}><FilmReel className={styles.reelLeft}/><div className={styles.countdownCopy}><span>COUNTING EVERY RAY</span><h2>Until Our Colors Meet</h2></div><div className={styles.countdownNums}>{xs.map(([v,l])=><div key={l}><strong>{String(v).padStart(2,"0")}</strong><span>{l}</span></div>)}</div><FilmReel className={styles.reelRight}/></div>}

function Events({invitation}:{invitation:InvitationData}){return <div className={styles.section}><Heading over="The Celebration" title="Where Light Becomes One"/><div className={styles.events}>{invitation.events.map((e,i)=><Reveal key={`${e.name}-${i}`} delay={i*.1}><article><div className={styles.eventTitle}><span>CELEBRATION 0{i+1}</span><h3>{e.name}</h3></div><div className={styles.eventBody}><time>{e.date}</time><b>{e.time}</b><p>{e.location}</p>{invitation.mapsUrl&&<a href={invitation.mapsUrl} target="_blank" rel="noreferrer">VIEW LOCATION →</a>}</div><div className={styles.eventCode}>VIP<br/>20•09•26</div></article></Reveal>)}</div></div>}

function Gallery({invitation}:{invitation:InvitationData}){const ps=invitation.gallery.slice(0,8);const[a,setA]=useState<number|null>(null);useEffect(()=>{if(a===null)return;const k=(e:KeyboardEvent)=>e.key==="Escape"&&setA(null);addEventListener("keydown",k);return()=>removeEventListener("keydown",k)},[a]);return <div className={styles.galleryBand}><div className={styles.section}><Heading over="Fragments Of Forever" title="The Prism Gallery" dark/><div className={styles.filmstrip}>{ps.map((p,i)=><Reveal key={p} delay={Math.min(i*.04,.25)}><button onClick={()=>setA(i)} aria-label={`Buka foto galeri ${i+1}`}><i/><img src={p} alt="" loading="lazy"/><span>REFRACTION {String(i+1).padStart(2,"0")}</span><b/></button></Reveal>)}</div></div><AnimatePresence>{a!==null&&<motion.div className={styles.lightbox} initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} onClick={()=>setA(null)}><button aria-label="Tutup galeri" onClick={()=>setA(null)}>×</button><img src={ps[a]} alt="" onClick={e=>e.stopPropagation()}/></motion.div>}</AnimatePresence></div>}

function Video({invitation}:{invitation:InvitationData}){if(!invitation.videoUrl)return null;return <div className={styles.section}><Heading over="Moving Memories" title="Our Story In Motion"/><Reveal><div className={styles.screen}><div/><iframe src={invitation.videoUrl} title="Video kedua mempelai" allowFullScreen/></div></Reveal></div>}
function Maps({invitation}:{invitation:InvitationData}){if(!invitation.mapsEmbedUrl&&!invitation.mapsUrl)return null;return <div className={`${styles.section} ${styles.maps}`}><Heading over="Sacred Coordinates" title="Follow The Light"/><Reveal><div className={styles.mapFrame}>{invitation.mapsEmbedUrl&&<iframe src={invitation.mapsEmbedUrl} title="Peta lokasi acara" loading="lazy"/>}<div><span>CELEBRATION LOCATION</span><b>{invitation.events[0]?.location}</b>{invitation.mapsUrl&&<a href={invitation.mapsUrl} target="_blank" rel="noreferrer">EXPLORE MAP →</a>}</div></div></Reveal></div>}

function GiftCard({g,c,copy}:{g:GiftAccount;c:boolean;copy:()=>void}){return <article className={styles.giftCard}><span>PRISMATIC VOWS</span><small>{g.owner}</small><h3>{g.bankName}</h3><strong>{g.accountNumber}</strong><p>a.n. {g.accountName}</p>{g.accountNumber&&<button onClick={copy}>{c?"COPIED ✓":"COPY ACCOUNT"}</button>}<FilmReel className={styles.giftReel}/></article>}
function Gift({invitation}:{invitation:InvitationData}){const[c,setC]=useState<number|null>(null);const cp=async(g:GiftAccount,i:number)=>{if(!g.accountNumber)return;await navigator.clipboard.writeText(g.accountNumber);setC(i);setTimeout(()=>setC(null),1500)};return <div className={styles.section}><Heading over="A Token Of Light" title="Gift Of Love"/><p className={styles.intro}>Doa restu Anda adalah hadiah terindah. Tanda kasih dapat disampaikan melalui rekening berikut.</p><div className={styles.gifts}>{invitation.gifts.map((g,i)=><Reveal key={`${g.owner}-${i}`} delay={i*.1}><GiftCard g={g} c={c===i} copy={()=>cp(g,i)}/></Reveal>)}</div></div>}

function RSVP({invitation}:{invitation:InvitationData}){const{counts,submit,submitting,submitted}=useRsvpWishes(invitation.id);const[n,setN]=useState("");const[w,setW]=useState("");const[a,setA]=useState<Attendance>("Hadir");const[m,setM]=useState("");const[e,setE]=useState("");const send=async(x:React.FormEvent)=>{x.preventDefault();setE("");if(!n.trim()||!m.trim()){setE("Nama dan ucapan wajib diisi.");return}const r=await submit({name:n,whatsapp:w,attendance:a,message:m});if(r.error){setE(r.error);return}setN("");setW("");setM("")};return <div className={styles.rsvpBand}><div className={styles.section}><Heading over="Your Presence Matters" title="Join Our Spectrum" dark/><div className={styles.rsvp}><div className={styles.seats}><Clapperboard className={styles.rsvpClap}/><h3>Guest Constellation</h3>{[[counts.hadir,"PRESENT"],[counts.tidakHadir,"ABSENT"],[counts.raguRagu,"UNSURE"]].map(([v,l])=><div key={l}><strong>{v}</strong><span>{l}</span></div>)}</div>{submitted?<div className={styles.confirmed}><span>✓</span><h3>Light Received</h3><p>See you where our colors meet.</p></div>:<form onSubmit={send}><label>Your Name<input value={n} onChange={x=>setN(x.target.value)} required/></label><label>WhatsApp<input value={w} onChange={x=>setW(x.target.value)}/></label><label>Attendance<select value={a} onChange={x=>setA(x.target.value as Attendance)}><option>Hadir</option><option>Tidak Hadir</option><option>Masih Ragu</option></select></label><label>Wishes In Color<textarea rows={4} value={m} onChange={x=>setM(x.target.value)} required/></label><button disabled={submitting}>{submitting?"RESERVING...":"SHARE YOUR LIGHT →"}</button>{e&&<p>{e}</p>}</form>}</div></div></div>}

function Wishes({invitation}:{invitation:InvitationData}){const{entries,totalCount,hasMore,loadMore}=useRsvpWishes(invitation.id);return <div className={styles.section}><Heading over="Echoes Of Love" title="Wishes Through The Prism"/>{totalCount===0?<p className={styles.empty}>Jadilah yang pertama memberikan ucapan.</p>:<><div className={styles.reviews}>{entries.map((x,i)=><Reveal key={x.id} delay={Math.min(i*.05,.25)}><article><span>★★★★★</span><p>“{x.message}”</p><div><b>{x.name}</b><small>{x.attendance}</small></div></article></Reveal>)}</div>{hasMore&&<button className={styles.more} onClick={loadMore}>MORE WISHES</button>}</>}</div>}
function Footer({invitation}:{invitation:InvitationData}){return <footer className={styles.footer}><div className={styles.footerCurtain}/><FilmReel className={styles.footerReel}/><span>REFRACTING YOUR LOVE STORY</span><h2>FOREVER</h2><p>IN EVERY LIGHT</p><div>{(invitation.groom.nickname || invitation.groom.name)}<i>&amp;</i>{(invitation.bride.nickname || invitation.bride.name)}</div><small>{invitation.brand?.logoUrl && <img src={invitation.brand.logoUrl} alt="" style={{height:16,verticalAlign:"middle",marginRight:6,display:"inline-block"}}/>}© {new Date().getFullYear()} {invitation.brand?.name??"Vistiq Invitation"}</small></footer>}
function Music({url}:{url:string|null}){const{audioRef,isPlaying,toggle}=useMusicPlayer(url);if(!url)return null;return <><audio ref={audioRef} src={url} loop/><button className={styles.music} onClick={toggle} aria-label={isPlaying?"Jeda musik":"Putar musik"}>{isPlaying?"Ⅱ":"♪"}</button></>}
const nav=[["home","Home"],["couple","Couple"],["story","Story"],["event","Event"],["gallery","Gallery"],["gift","Gift"],["rsvp","RSVP"]];function Menu(){return <nav className={styles.menu} aria-label="Navigasi undangan">{nav.map(([id,l])=><button key={id} onClick={()=>document.getElementById(id)?.scrollIntoView({behavior:"smooth"})}><span>●</span>{l}</button>)}</nav>}
export default function PrismaticVows({invitation}:{invitation:InvitationData}){const{opened}=useInvitation();const[ready,setReady]=useState(false);useEffect(()=>{const t=setTimeout(()=>setReady(true),850);return()=>clearTimeout(t)},[]);const date=invitation.events[0]?.rawDate;return <div className={styles.root}><AnimatePresence>{!ready&&<Loading key="load"/>}</AnimatePresence>{ready&&!opened&&<Cover invitation={invitation}/>} {ready&&opened&&<><section id="home"><Opening invitation={invitation}/></section><section id="couple"><Couple invitation={invitation}/></section>{invitation.story.length>0&&<section id="story"><Story invitation={invitation}/></section>}{date&&<Countdown date={date}/>}<section id="event"><Events invitation={invitation}/></section>{invitation.gallery.length>0&&<section id="gallery"><Gallery invitation={invitation}/></section>}<Video invitation={invitation}/><section id="maps"><Maps invitation={invitation}/></section>{invitation.gifts.length>0&&<section id="gift"><Gift invitation={invitation}/></section>}<section id="rsvp"><RSVP invitation={invitation}/></section><Wishes invitation={invitation}/><Footer invitation={invitation}/><Music url={invitation.musicUrl}/><Menu/></>}</div>}
