"use client";

import { useCallback, useRef } from "react";
import type { InvitationData } from "@/types/invitation";
import styles from "./style.module.css";

const REFERENCE_PAGE = "/themes/ivory-botanica/reference/index.html";
const REFERENCE_DATE = "Minggu, 20 September 2026";
const LEGACY_REFERENCE_DATE = "Senin, 28 Desember 2026";
const VISTIQ_INSTAGRAM_URL = "https://www.instagram.com/vistiqinvitation/";
const VISTIQ_ADMIN_WHATSAPP_URL = "https://wa.me/6281371338032";

type FooterIconKind = "instagram" | "whatsapp";
const FOOTER_ICON_MARKUP: Record<FooterIconKind, string> = {
  instagram:'<rect x="3.25" y="3.25" width="17.5" height="17.5" rx="4.5" fill="none" stroke="currentColor" stroke-width="1.8"/><circle cx="12" cy="12" r="4.1" fill="none" stroke="currentColor" stroke-width="1.8"/><circle cx="17.45" cy="6.65" r="1.05" fill="currentColor"/>',
  whatsapp:'<path fill="currentColor" d="M16.04 3C8.86 3 3.03 8.73 3.03 15.79c0 2.25.6 4.45 1.74 6.38L3 28.55l6.6-1.7a13.1 13.1 0 0 0 6.43 1.63h.01c7.17 0 13.01-5.74 13.01-12.79C29.05 8.64 23.21 3 16.04 3Zm0 23.32h-.01a10.9 10.9 0 0 1-5.55-1.49l-.4-.23-3.92 1.01 1.05-3.75-.26-.39a10.5 10.5 0 0 1-1.68-5.68c0-5.87 4.83-10.64 10.78-10.64 5.94 0 10.77 4.77 10.77 10.64 0 5.86-4.84 10.53-10.78 10.53Z"/>'
};
type TimerElement = HTMLElement & { __idbTimer?: number };

function shortName(person: InvitationData["groom"]){return person.nickname?.trim()||person.name.trim().split(/\s+/)[0]||"Mempelai"}
function instagramUrl(value:string|null){const h=value?.trim().replace(/^@/,"");return h?`https://instagram.com/${h}`:"https://www.instagram.com/"}
function instagramHandle(value:string|null){return value?.trim().replace(/^@/,"")||""}
function parentParts(value:string|null){const p=(value||"").split(/\s*&\s*/).map(x=>x.trim()).filter(Boolean);return[p[0]||"",p[1]||""]}
function replaceText(d:Document,from:string,to:string){if(!from||from===to||!d.body)return;const w=d.createTreeWalker(d.body,NodeFilter.SHOW_TEXT),nodes:Text[]=[];let n=w.nextNode();while(n){nodes.push(n as Text);n=w.nextNode()}nodes.forEach(t=>{if(t.nodeValue?.includes(from))t.nodeValue=t.nodeValue.replaceAll(from,to)})}
function currentGuest(){if(typeof window==="undefined")return "Bapak/Ibu/Saudara/i";return new URLSearchParams(window.location.search).get("to")?.trim()||"Bapak/Ibu/Saudara/i"}
function setGuestName(d:Document,guest:string){const marker=d.querySelector<HTMLElement>(".elementor-element-633aaeac .elementor-widget-container");if(marker)marker.textContent=guest;else replaceText(d,"Nama Tamu",guest)}

function setEditableOpening(d:Document, invitation:InvitationData){
  const quote=invitation.opening.quote?.trim();const source=invitation.opening.quoteSource?.trim();const description=invitation.opening.description?.trim();const greeting=invitation.opening.greeting?.trim();if(!quote&&!source&&!description&&!greeting)return;
  let block=d.getElementById("vistiq-editable-opening");if(!block){block=d.createElement("section");block.id="vistiq-editable-opening";const event=d.querySelector(".acara-con");const target=event?.parentElement||d.querySelector("main")||d.body;if(event&&event.parentElement)event.parentElement.insertBefore(block,event);else target?.appendChild(block)}
  block.innerHTML="";Object.assign(block.style,{padding:"42px 24px",textAlign:"center",background:"#f7f3e8",color:"#4b4337",fontFamily:"inherit"});
  if(greeting){const el=d.createElement("h3");el.textContent=greeting;Object.assign(el.style,{margin:"0 0 16px",fontSize:"22px",fontWeight:"500"});block.appendChild(el)}
  if(description){const el=d.createElement("p");el.textContent=description;Object.assign(el.style,{maxWidth:"620px",margin:"0 auto 22px",lineHeight:"1.8",fontSize:"15px",whiteSpace:"pre-line"});block.appendChild(el)}
  if(quote){quote.split(/\n\s*\n/).map(x=>x.trim()).filter(Boolean).forEach((part,index)=>{const el=d.createElement("p");el.textContent=part;const arabic=/[\u0600-\u06FF]/.test(part);if(arabic){el.dir="rtl";el.lang="ar"}Object.assign(el.style,{maxWidth:"700px",margin:index===0?"0 auto 18px":"0 auto 12px",lineHeight:arabic?"2.15":"1.8",fontSize:arabic?"24px":"15px",fontFamily:arabic?'"Noto Naskh Arabic","Amiri","Scheherazade New",serif':"inherit",whiteSpace:"pre-line"});block!.appendChild(el)})}
  if(source){const el=d.createElement("p");el.textContent=source;Object.assign(el.style,{margin:"14px auto 0",fontWeight:"600",fontSize:"14px"});block.appendChild(el)}
}

function setCountdown(d:Document,rawDate:string|null){const c=d.querySelector<HTMLElement>(".idb-countdown");if(!c||!rawDate)return;const target=new Date(rawDate).getTime();if(!Number.isFinite(target))return;const t=c as TimerElement,w=d.defaultView;if(t.__idbTimer&&w)w.clearInterval(t.__idbTimer);const update=()=>{const r=Math.max(0,target-Date.now()),v={days:Math.floor(r/86400000),hours:Math.floor((r%86400000)/3600000),minutes:Math.floor((r%3600000)/60000),seconds:Math.floor((r%60000)/1000)};Object.entries(v).forEach(([p,x])=>{const e=c.querySelector<HTMLElement>(`.idb-countdown__item[data-part="${p}"] [data-role="num"]`);if(e)e.textContent=p==="days"?String(x):String(x).padStart(2,"0")})};update();if(w)t.__idbTimer=w.setInterval(update,1000)}
function setEventContent(root:HTMLElement,event:InvitationData["events"][number]){const m=root.querySelector<HTMLElement>(".nama-acara-marker");if(m)m.textContent=event.name;const e=Array.from(root.querySelectorAll<HTMLElement>(".elementor-widget-text-editor .elementor-widget-container"));if(e[0])e[0].textContent=event.date;if(e[1])e[1].textContent=`Pukul : ${event.time}`;if(e[2])e[2].textContent=`Tempat : ${event.location}`;root.querySelectorAll<HTMLAnchorElement>("a[data-idb-maps-link]").forEach(a=>{if(event.mapsUrl?.trim()){a.href=event.mapsUrl;a.style.removeProperty("display");a.removeAttribute("aria-hidden")}else{a.removeAttribute("href");a.style.display="none"}})}
function ensureEventRoots(d:Document,count:number){const target=Math.min(Math.max(count,0),4),roots=Array.from(d.querySelectorAll<HTMLElement>(".acara-con"));if(!roots.length)return roots;let last=roots[roots.length-1];while(roots.length<target){const c=last.cloneNode(true) as HTMLElement;c.removeAttribute("id");c.querySelectorAll<HTMLElement>("[id]").forEach(n=>n.removeAttribute("id"));last.insertAdjacentElement("afterend",c);roots.push(c);last=c}roots.forEach((r,i)=>r.style.display=i<target?"":"none");return roots}
function setParents(d:Document,side:"pria"|"wanita",parents:string|null){const [f,m]=parentParts(parents),x=Array.from(d.querySelectorAll<HTMLElement>(`[data-idb-mempelai-side="${side}"]`));if(x[0])x[0].textContent=f;if(x[1])x[1].textContent=m}
function localizeInternalLinks(d:Document){d.querySelectorAll<HTMLAnchorElement>('a[href*="inv.wekita.id/spesial-02-animasi/#"]').forEach(a=>{const h=a.getAttribute("href")||"",i=h.indexOf("#"),hash=i>=0?decodeURIComponent(h.slice(i+1)).trim():"";a.href=/#(?:%20|\s*)$/i.test(h)?"#amplop":hash?`#${hash}`:"#home"})}

function setAudioSource(d:Document,url:string|null){
  const existing=d.getElementById("vistiq-music-control");
  if(!url){existing?.remove();return}
  const audios=Array.from(d.querySelectorAll<HTMLAudioElement>(".idb-audio-el"));
  audios.forEach(a=>{a.pause();a.autoplay=false;a.removeAttribute("autoplay");const s=a.querySelector<HTMLSourceElement>("source");if(s)s.src=url;a.src=url;a.loop=true;a.preload="metadata";a.load()});
  const primary=audios[0];if(!primary)return;
  let opened=false;
  let control=existing as HTMLButtonElement|null;
  if(!control){control=d.createElement("button");control.id="vistiq-music-control";control.type="button";control.setAttribute("aria-label","Putar musik");control.textContent="▶";Object.assign(control.style,{position:"fixed",right:"18px",bottom:"22px",zIndex:"999999",width:"44px",height:"44px",borderRadius:"50%",border:"0",background:"rgba(78,112,91,.92)",color:"#fff",fontSize:"18px",lineHeight:"44px",textAlign:"center",boxShadow:"0 4px 14px rgba(0,0,0,.22)",cursor:"pointer",display:"none",padding:"0"});d.body.appendChild(control)}
  const sync=()=>{if(!control)return;const playing=!primary.paused;control.textContent=playing?"❚❚":"▶";control.setAttribute("aria-label",playing?"Jeda musik":"Putar musik")};
  primary.addEventListener("play",sync);primary.addEventListener("pause",sync);
  control.onclick=()=>{if(!opened)return;if(primary.paused)primary.play().catch(()=>{});else primary.pause();sync()};
  const open=d.getElementById("open");
  if(open&&!open.dataset.vistiqMusicBound){open.dataset.vistiqMusicBound="1";open.addEventListener("click",()=>{opened=true;if(control)control.style.display="block";const start=Number(primary.closest<HTMLElement>(".idb-audio-box")?.dataset.start||0);if(Number.isFinite(start)&&start>0&&primary.currentTime<1){try{primary.currentTime=start}catch{}}primary.volume=.8;primary.play().then(sync).catch(sync)},{capture:true})}
}
function createFooterIcon(d:Document,kind:FooterIconKind){const s=d.createElementNS("http://www.w3.org/2000/svg","svg");s.setAttribute("viewBox",kind==="whatsapp"?"0 0 32 32":"0 0 24 24");s.setAttribute("width","24");s.setAttribute("height","24");s.innerHTML=FOOTER_ICON_MARKUP[kind];return s}
function setFooterBranding(d:Document){const f=d.querySelector<HTMLElement>(".elementor-element-12b47c4c");if(!f)return;const w=f.querySelector<HTMLAnchorElement>('a[aria-label="WhatsApp"]');if(w){w.href=VISTIQ_ADMIN_WHATSAPP_URL;w.replaceChildren(createFooterIcon(d,"whatsapp"))}const i=f.querySelector<HTMLAnchorElement>('a[aria-label="Instagram"]');if(i){i.href=VISTIQ_INSTAGRAM_URL;i.replaceChildren(createFooterIcon(d,"instagram"))}}
function applyOptionalSectionVisibility(d:Document,i:InvitationData){if(!d.body)return;const hasStory=i.story.some(x=>Boolean(x.title?.trim()||x.description?.trim()||x.year?.trim()));const hasLiveStreaming=Boolean(i.liveStreamingUrl?.trim());const hasGift=i.gifts.some(g=>Boolean(g.bankName?.trim()||g.accountNumber?.trim()||g.accountName?.trim()));d.body.classList.toggle("idb-hide-love-story",!hasStory);d.body.classList.toggle("idb-hide-live-streaming",!hasLiveStreaming);d.body.classList.toggle("idb-hide-wedding-gift",!hasGift);d.body.classList.toggle("idb-hide-kirim-hadiah",!hasGift);if(!hasGift){d.querySelectorAll<HTMLElement>("#amplop, .amplop-con, .gift-con, .wedding-gift-con, .kirim-hadiah-con, [data-idb-section='amplop'], [data-idb-section='gift']").forEach(el=>{el.style.display="none";el.setAttribute("aria-hidden","true")});d.querySelectorAll<HTMLAnchorElement>('a[href="#amplop"], a[href*="#amplop"]').forEach(a=>{a.style.display="none";a.setAttribute("aria-hidden","true")})}}
function applyInvitationData(d:Document,i:InvitationData,guest:string){const gs=shortName(i.groom),bs=shortName(i.bride),first=i.events[0],cover=i.coverEvent||first;d.title=`${gs} & ${bs} — Ivory Botanica`;d.documentElement.lang="id";applyOptionalSectionVisibility(d,i);replaceText(d,"Habib & Adiba",`${gs} & ${bs}`);replaceText(d,"Rizky & Nabila",`${gs} & ${bs}`);replaceText(d,"Habib Yulianto",i.groom.name);replaceText(d,"Rizky Pratama",i.groom.name);replaceText(d,"Adiba Putri Syakila",i.bride.name);replaceText(d,"Nabila Putri",i.bride.name);setGuestName(d,guest);replaceText(d,LEGACY_REFERENCE_DATE,cover?.date||REFERENCE_DATE);replaceText(d,REFERENCE_DATE,cover?.date||REFERENCE_DATE);setParents(d,"pria",i.groom.parents);setParents(d,"wanita",i.bride.parents);const roots=ensureEventRoots(d,i.events.length);i.events.slice(0,roots.length).forEach((e,n)=>setEventContent(roots[n],e));const inst=Array.from(d.querySelectorAll<HTMLAnchorElement>('.elementor-widget-bisdev_social_icons a[aria-label="Instagram"]')),vals=[i.groom.instagram,i.bride.instagram,i.groom.instagram];inst.forEach((a,n)=>{const v=vals[n]||null;a.href=instagramUrl(v);const l=a.querySelector<HTMLElement>(".idb-social-icons__text"),h=instagramHandle(v);if(l&&h)l.textContent=`@${h}`});setEditableOpening(d,i);setAudioSource(d,i.musicUrl);setCountdown(d,cover?.rawDate||first?.rawDate||null);localizeInternalLinks(d);setFooterBranding(d);if(!d.getElementById("ivory-botanica-frame-overrides")){const s=d.createElement("style");s.id="ivory-botanica-frame-overrides";s.textContent=":root,body{background-color:#f7f3e8!important}.idb-hide-wedding-gift #amplop,.idb-hide-wedding-gift .amplop-con,.idb-hide-wedding-gift .gift-con,.idb-hide-wedding-gift .wedding-gift-con,.idb-hide-kirim-hadiah .kirim-hadiah-con{display:none!important}";d.head.appendChild(s)}}

export default function IvoryBotanica({invitation}:{invitation:InvitationData}){const ref=useRef<HTMLIFrameElement>(null);const handleLoad=useCallback(()=>{const d=ref.current?.contentDocument;if(d)applyInvitationData(d,invitation,currentGuest())},[invitation]);return <div className={styles.root}><iframe ref={ref} className={styles.frame} src={REFERENCE_PAGE} title={`Undangan ${shortName(invitation.groom)} dan ${shortName(invitation.bride)}`} allow="autoplay; fullscreen; picture-in-picture" onLoad={handleLoad}/></div>}
