"use client";

import { useCallback, useRef } from "react";
import type { InvitationData } from "@/types/invitation";
import styles from "./style.module.css";

const REFERENCE_PAGE = "/themes/ivory-botanica/reference/index.html";
const REFERENCE_DATE = "Minggu, 20 September 2026";
const LEGACY_REFERENCE_DATE = "Senin, 28 Desember 2026";
const VISTIQ_INSTAGRAM_URL = "https://www.instagram.com/vistiqinvitation/";
const VISTIQ_ADMIN_WHATSAPP_URL = "https://wa.me/6281371338032";
type FooterIconKind="instagram"|"whatsapp";
const FOOTER_ICON_MARKUP:Record<FooterIconKind,string>={instagram:'<rect x="3.25" y="3.25" width="17.5" height="17.5" rx="4.5" fill="none" stroke="currentColor" stroke-width="1.8"/><circle cx="12" cy="12" r="4.1" fill="none" stroke="currentColor" stroke-width="1.8"/><circle cx="17.45" cy="6.65" r="1.05" fill="currentColor"/>',whatsapp:'<path fill="currentColor" d="M16.04 3C8.86 3 3.03 8.73 3.03 15.79c0 2.25.6 4.45 1.74 6.38L3 28.55l6.6-1.7a13.1 13.1 0 0 0 6.43 1.63h.01c7.17 0 13.01-5.74 13.01-12.79C29.05 8.64 23.21 3 16.04 3Zm0 23.32h-.01a10.9 10.9 0 0 1-5.55-1.49l-.4-.23-3.92 1.01 1.05-3.75-.26-.39a10.5 10.5 0 0 1-1.68-5.68c0-5.87 4.83-10.64 10.78-10.64 5.94 0 10.77 4.77 10.77 10.64 0 5.86-4.84 10.53-10.78 10.53Z"/>'};
type TimerElement=HTMLElement&{__idbTimer?:number};
function shortName(p:InvitationData["groom"]){return p.nickname?.trim()||p.name.trim().split(/\s+/)[0]||"Mempelai"}
function instagramUrl(v:string|null){const h=v?.trim().replace(/^@/,"");return h?`https://instagram.com/${h}`:"https://www.instagram.com/"}
function instagramHandle(v:string|null){return v?.trim().replace(/^@/,"")||""}
function parentParts(v:string|null){const p=(v||"").split(/\s*&\s*/).map(x=>x.trim()).filter(Boolean);return[p[0]||"",p[1]||""]}
function replaceText(d:Document,f:string,t:string){if(!f||f===t||!d.body)return;const w=d.createTreeWalker(d.body,NodeFilter.SHOW_TEXT),a:Text[]=[];let n=w.nextNode();while(n){a.push(n as Text);n=w.nextNode()}a.forEach(x=>{if(x.nodeValue?.includes(f))x.nodeValue=x.nodeValue.replaceAll(f,t)})}
function currentGuest(){if(typeof window==="undefined")return"Bapak/Ibu/Saudara/i";return new URLSearchParams(window.location.search).get("to")?.trim()||"Bapak/Ibu/Saudara/i"}
function setGuestName(d:Document,g:string){const m=d.querySelector<HTMLElement>(".elementor-element-633aaeac .elementor-widget-container");if(m)m.textContent=g;else replaceText(d,"Nama Tamu",g)}
function setEditableOpening(d:Document,i:InvitationData){const q=i.opening.quote?.trim(),s=i.opening.quoteSource?.trim(),x=i.opening.description?.trim(),g=i.opening.greeting?.trim();if(!q&&!s&&!x&&!g)return;let b=d.getElementById("vistiq-editable-opening");if(!b){b=d.createElement("section");b.id="vistiq-editable-opening";const e=d.querySelector(".acara-con"),t=e?.parentElement||d.querySelector("main")||d.body;if(e&&e.parentElement)e.parentElement.insertBefore(b,e);else t?.appendChild(b)}b.innerHTML="";Object.assign(b.style,{padding:"42px 24px",textAlign:"center",background:"#f7f3e8",color:"#4b4337",fontFamily:"inherit"});if(g){const e=d.createElement("h3");e.textContent=g;Object.assign(e.style,{margin:"0 0 16px",fontSize:"22px",fontWeight:"500"});b.appendChild(e)}if(x){const e=d.createElement("p");e.textContent=x;Object.assign(e.style,{maxWidth:"620px",margin:"0 auto 22px",lineHeight:"1.8",fontSize:"15px",whiteSpace:"pre-line"});b.appendChild(e)}if(q)q.split(/\n\s*\n/).map(v=>v.trim()).filter(Boolean).forEach((v,k)=>{const e=d.createElement("p"),ar=/[\u0600-\u06FF]/.test(v);e.textContent=v;if(ar){e.dir="rtl";e.lang="ar"}Object.assign(e.style,{maxWidth:"700px",margin:k===0?"0 auto 18px":"0 auto 12px",lineHeight:ar?"2.15":"1.8",fontSize:ar?"24px":"15px",fontFamily:ar?'"Noto Naskh Arabic","Amiri",serif':"inherit",whiteSpace:"pre-line"});b!.appendChild(e)});if(s){const e=d.createElement("p");e.textContent=s;Object.assign(e.style,{margin:"14px auto 0",fontWeight:"600",fontSize:"14px"});b.appendChild(e)}}
function setCountdown(d:Document,r:string|null){const c=d.querySelector<HTMLElement>(".idb-countdown");if(!c||!r)return;const z=new Date(r).getTime();if(!Number.isFinite(z))return;const t=c as TimerElement,w=d.defaultView;if(t.__idbTimer&&w)w.clearInterval(t.__idbTimer);const u=()=>{const r=Math.max(0,z-Date.now()),v={days:Math.floor(r/86400000),hours:Math.floor((r%86400000)/3600000),minutes:Math.floor((r%3600000)/60000),seconds:Math.floor((r%60000)/1000)};Object.entries(v).forEach(([p,x])=>{const e=c.querySelector<HTMLElement>(`.idb-countdown__item[data-part="${p}"] [data-role="num"]`);if(e)e.textContent=p==="days"?String(x):String(x).padStart(2,"0")})};u();if(w)t.__idbTimer=w.setInterval(u,1000)}
function setEventContent(r:HTMLElement,e:InvitationData["events"][number]){const m=r.querySelector<HTMLElement>(".nama-acara-marker");if(m)m.textContent=e.name;const a=Array.from(r.querySelectorAll<HTMLElement>(".elementor-widget-text-editor .elementor-widget-container"));if(a[0])a[0].textContent=e.date;if(a[1])a[1].textContent=`Pukul : ${e.time}`;if(a[2])a[2].textContent=`Tempat : ${e.location}`;r.querySelectorAll<HTMLAnchorElement>("a[data-idb-maps-link]").forEach(x=>{if(e.mapsUrl?.trim()){x.href=e.mapsUrl;x.style.removeProperty("display")}else{x.removeAttribute("href");x.style.display="none"}})}
function ensureEventRoots(d:Document,n:number){const t=Math.min(Math.max(n,0),4),r=Array.from(d.querySelectorAll<HTMLElement>(".acara-con"));if(!r.length)return r;let l=r[r.length-1];while(r.length<t){const c=l.cloneNode(true)as HTMLElement;c.removeAttribute("id");c.querySelectorAll<HTMLElement>("[id]").forEach(x=>x.removeAttribute("id"));l.insertAdjacentElement("afterend",c);r.push(c);l=c}r.forEach((x,k)=>x.style.display=k<t?"":"none");return r}
function setParents(d:Document,s:"pria"|"wanita",p:string|null){const[f,m]=parentParts(p),x=Array.from(d.querySelectorAll<HTMLElement>(`[data-idb-mempelai-side="${s}"]`));if(x[0])x[0].textContent=f;if(x[1])x[1].textContent=m}
function localizeInternalLinks(d:Document){d.querySelectorAll<HTMLAnchorElement>('a[href*="inv.wekita.id/spesial-02-animasi/#"]').forEach(a=>{const h=a.getAttribute("href")||"",i=h.indexOf("#"),x=i>=0?decodeURIComponent(h.slice(i+1)).trim():"";a.href=/#(?:%20|\s*)$/i.test(h)?"#amplop":x?`#${x}`:"#home"})}
function setAudioSource(d:Document,url:string|null){
  d.querySelectorAll<HTMLAudioElement>(".idb-audio-el").forEach(a=>{a.pause();a.muted=true});
  const old=d.getElementById("vistiq-dedicated-audio") as HTMLAudioElement|null;
  const oldBtn=d.getElementById("vistiq-music-control") as HTMLButtonElement|null;
  if(!url){old?.remove();oldBtn?.remove();return}
  const audio=old||d.createElement("audio");audio.id="vistiq-dedicated-audio";audio.src=url;audio.loop=true;audio.preload="auto";audio.autoplay=false;audio.volume=.8;audio.setAttribute("playsinline","");if(!old)d.body.appendChild(audio);else if(audio.src!==url)audio.src=url;
  let btn=oldBtn;if(!btn){btn=d.createElement("button");btn.id="vistiq-music-control";btn.type="button";Object.assign(btn.style,{position:"fixed",right:"18px",bottom:"130px",zIndex:"2147483647",width:"46px",height:"46px",borderRadius:"50%",border:"0",background:"#5f7f6c",color:"#fff",fontSize:"19px",fontWeight:"700",boxShadow:"0 4px 16px rgba(0,0,0,.28)",display:"none",alignItems:"center",justifyContent:"center",padding:"0",cursor:"pointer"});d.body.appendChild(btn)}
  let opened=false;const sync=()=>{if(!btn)return;btn.textContent=audio.paused?"▶":"Ⅱ";btn.setAttribute("aria-label",audio.paused?"Putar musik":"Jeda musik")};sync();audio.onplay=sync;audio.onpause=sync;btn.onclick=()=>{if(!opened)return;if(audio.paused)audio.play().catch(()=>{});else audio.pause()};
  const open=d.getElementById("open");if(open&&!open.dataset.vistiqDedicatedMusic){open.dataset.vistiqDedicatedMusic="1";open.addEventListener("click",()=>{opened=true;if(btn)btn.style.display="flex";if(audio.currentTime<1)try{audio.currentTime=15}catch{}audio.play().catch(()=>{sync()})},{capture:true})}
}
function createFooterIcon(d:Document,k:FooterIconKind){const s=d.createElementNS("http://www.w3.org/2000/svg","svg");s.setAttribute("viewBox",k==="whatsapp"?"0 0 32 32":"0 0 24 24");s.setAttribute("width","24");s.setAttribute("height","24");s.innerHTML=FOOTER_ICON_MARKUP[k];return s}
function setFooterBranding(d:Document){const f=d.querySelector<HTMLElement>(".elementor-element-12b47c4c");if(!f)return;const w=f.querySelector<HTMLAnchorElement>('a[aria-label="WhatsApp"]');if(w){w.href=VISTIQ_ADMIN_WHATSAPP_URL;w.replaceChildren(createFooterIcon(d,"whatsapp"))}const i=f.querySelector<HTMLAnchorElement>('a[aria-label="Instagram"]');if(i){i.href=VISTIQ_INSTAGRAM_URL;i.replaceChildren(createFooterIcon(d,"instagram"))}}
function applyOptionalSectionVisibility(d:Document,i:InvitationData){if(!d.body)return;const s=i.story.some(x=>Boolean(x.title?.trim()||x.description?.trim()||x.year?.trim())),l=Boolean(i.liveStreamingUrl?.trim()),g=i.gifts.some(x=>Boolean(x.bankName?.trim()||x.accountNumber?.trim()||x.accountName?.trim()));d.body.classList.toggle("idb-hide-love-story",!s);d.body.classList.toggle("idb-hide-live-streaming",!l);d.body.classList.toggle("idb-hide-wedding-gift",!g);d.body.classList.toggle("idb-hide-kirim-hadiah",!g);if(!g)d.querySelectorAll<HTMLElement>("#amplop,.amplop-section,.gift-con,.wedding-gift-con,.kirim-hadiah-con").forEach(e=>e.style.display="none")}
function applyInvitationData(d:Document,i:InvitationData,g:string){const gs=shortName(i.groom),bs=shortName(i.bride),f=i.events[0],c=i.coverEvent||f;d.title=`${gs} & ${bs} — Ivory Botanica`;d.documentElement.lang="id";applyOptionalSectionVisibility(d,i);replaceText(d,"Habib & Adiba",`${gs} & ${bs}`);replaceText(d,"Rizky & Nabila",`${gs} & ${bs}`);replaceText(d,"Habib Yulianto",i.groom.name);replaceText(d,"Rizky Pratama",i.groom.name);replaceText(d,"Adiba Putri Syakila",i.bride.name);replaceText(d,"Nabila Putri",i.bride.name);setGuestName(d,g);replaceText(d,LEGACY_REFERENCE_DATE,c?.date||REFERENCE_DATE);replaceText(d,REFERENCE_DATE,c?.date||REFERENCE_DATE);setParents(d,"pria",i.groom.parents);setParents(d,"wanita",i.bride.parents);const r=ensureEventRoots(d,i.events.length);i.events.slice(0,r.length).forEach((e,n)=>setEventContent(r[n],e));const a=Array.from(d.querySelectorAll<HTMLAnchorElement>('.elementor-widget-bisdev_social_icons a[aria-label="Instagram"]')),v=[i.groom.instagram,i.bride.instagram,i.groom.instagram];a.forEach((x,n)=>{const q=v[n]||null;x.href=instagramUrl(q);const l=x.querySelector<HTMLElement>(".idb-social-icons__text"),h=instagramHandle(q);if(l&&h)l.textContent=`@${h}`});setEditableOpening(d,i);setAudioSource(d,i.musicUrl);setCountdown(d,c?.rawDate||f?.rawDate||null);localizeInternalLinks(d);setFooterBranding(d)}
export default function IvoryBotanica({invitation}:{invitation:InvitationData}){const ref=useRef<HTMLIFrameElement>(null);const handleLoad=useCallback(()=>{const d=ref.current?.contentDocument;if(d)applyInvitationData(d,invitation,currentGuest())},[invitation]);return <div className={styles.root}><iframe ref={ref} className={styles.frame} src={REFERENCE_PAGE} title={`Undangan ${shortName(invitation.groom)} dan ${shortName(invitation.bride)}`} allow="autoplay; fullscreen; picture-in-picture" onLoad={handleLoad}/></div>}
